name: 2. Cleaning CSV Operations

on: 
  workflow_dispatch:

jobs:
  rscript_job:
    runs-on: ubuntu-latest
    steps:
    - name: List current dir....
      run: ls -la "/home/runner/work/Capstone-Analysis/Capstone-Analysis"
    
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content
  
    - name: Unzip Files
      run: |
        wget -O Uncleaned_Datasets.zip https://github.com/armonbc/Capstone-Analysis/archive/refs/tags/v2023.03.01.Uncleaned_Datasets.zip
        pwd && ls -la
        unzip "Uncleaned_Datasets.zip" -d "original_datasets"
        pwd && ls -la "original_datasets/"
    
    - name: Cache R Packages
      uses: actions/cache@v2
      with:
        path: /usr/local/lib/R/site-library
        key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: |
          ${{ runner.os }}-r-
    
    - name: Install R and its Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install r-base r-cran-ggplot2 r-cran-dplyr r-cran-tidyr r-cran-readr r-cran-tibble r-cran-stringr r-cran-forcats r-cran-purrr r-cran-httr r-cran-jsonlite r-cran-lubridate r-cran-xml2 r-cran-rlang r-cran-lazyeval r-cran-broom r-cran-modelr r-cran-ggthemes r-cran-farver r-cran-labeling r-cran-munsell r-cran-plyr r-cran-scales r-cran-colorspace r-cran-viridis r-cran-gtable r-cran-gridextra r-cran-cowplot r-cran-ggrepel r-cran-ggpubr r-cran-tidyverse

    - name: Cleaning CSV files
      run: |
        cd "Rscripts" && Rscript dataset_sortfilterlog.R
        zip -r cleaned_datasets.zip cleaned_datasets

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cleaned_datasets.zip
        tag_name: v2023.03.01.Cleaned_Datasets
        name: Cleaned Datasets (2022-02 to 2023-03)
        body: |
          This is the second release of our project.
          It includes several cleaned datasets.
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
