name: LFS Tracking Operations

on: 
  workflow_dispatch:

jobs:
  lfs_job:
    runs-on: ubuntu-latest
    steps:
    - name: List current dir....
      run: ls -la "/home/runner/work/Capstone-Analysis/Capstone-Analysis"
    
    - name: checkout repo content
      uses: actions/checkout@v3
    
    - name: Retain only 100mb+ files on LFS
      run: |
        git lfs untrack '*.csv'
        git rm --cached '*.csv'
        git add *.yml
        git commit -m "restore"
