name: Testing Only

on: 
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: 1. List current dir....
      run: ls -la && pwd
    
    - name: chang directory
      run: cd ../ && ls -la && pwd
    
    - name: 2. List current dir....
      run: ls -la && pwd
