name: Testing Only

on: 
  push:
    branches: main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v3 # checkout the repository content
  
    - name: List current dir....
      run: ls -la "/usr/local/lib/R/site-library"
    - name: Removing existing R
      run: |
         sudo apt-get remove r-base-core
         sudo apt-get remove r-base
         sudo apt-get autoremove
         sudo rm -rf /usr/local/lib/R/site-library
         sudo rm -rf /usr/lib/R/site-library
         sudo rm -rf /usr/lib/R/library
    - name: Cache R Packages
      uses: actions/cache@v3
      with:
        path: |
          /usr/lib/R/
        key: ${{ runner.os }}-cran-packages-${{ hashFiles('/usr/share/doc/r-base/') }}
        restore-keys: ${{ runner.os }}-cran-packages-
    
    - name: Install R and its Dependencies
      run: |
         sudo apt-get install r-base r-base-core r-cran-tidyverse
   
    - name: List current dir....
      run: |
        ls -la "/usr/local/lib/R/site-library"
        which R && whoami
      
    - name: Test R
      run: |
        cd Rscripts && Rscript dataset_prepare.R
    
