name: Testing Only

on: 
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out repo
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: r-lib/actions/setup-pkgdown@v3
      with:
        package: .
        dependencies: CRAN
    - name: Running Rscript
      run: |
        cd Rscripts && Rscript dataset_prepare.R
