name: Testing Only

on: 
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v3 # checkout the repository content
  
    - name: List current dir....
      run: ls -la "/home/runner/work/Capstone-Analysis/Capstone-Analysis"
      
    - name: Cache R Packages
      uses: actions/cache@v3
      with:
        path: |
          /usr/lib/R/site-library/tidyverse
        key: ${{ runner.os }}-cran-packages-${{ hashFiles('/usr/share/doc/r-base/') }}
        restore-keys: ${{ runner.os }}-cran-packages-
    #- name: Test R
    #  run: |
    #    cd Rscripts && Rscript dataset_prepare.R
    
    - name: Install R and its Dependencies
      run: |
        sudo apt-get install r-cran-tidyverse
    
