name: Zip File Download Operations

on: 
  workflow_dispatch:

jobs:
  python_job:
    runs-on: ubuntu-latest
    steps:
    - name: List current dir....
      run: ls -la "/home/runner/work/Capstone-Analysis/Capstone-Analysis"
    
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed

    - name: Install python packages....
      run: |
          python -m pip install --upgrade pip
          pip3 install bs4 requests lxml
          sudo apt install clang

    - name: Executing Python....
      run: |
          python3 Pythonscripts/all_zip_downloader.py
      
    - name: Zip Files
      run: |
        zip -r files.zip "../original_zipfiles/"
        ls -la "../original_zipfiles/"
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: zip-files
        path: ./files.zip
