name: Zip File Extraction Operations

on: 
  workflow_dispatch:

jobs:
  extraction_job:
    runs-on: ubuntu-latest
    steps:
    - name: List current dir....
      run: ls -la "/home/runner/work/Capstone-Analysis/Capstone-Analysis"
    
    - name: checkout repo content
      uses: actions/checkout@v3
      
    - name: Extracting Zip Files
      run: |
        # unzip -o "original_zipfiles/*" -d "original_datasets/${filename%.*}"
        find . -type f -name "original_zipfiles/*.zip" -exec sh -c 'unzip -d "original_datasets/$(basename {} .zip)" -o {}' \;
        ls -la "original_datasets/"
    
    - name: Configure Git
      env:
        USER_NAME: ${{secrets.GH_NAME}}
        USER_MAIL: ${{secrets.GH_EMAIL}} 
        USER_TOKEN: ${{secrets.PUBLIC_REPO_ACCESS_TOKEN}}
        GITHUB_TOKEN: $USER_TOKEN
      run: |
        git config --global user.name USER_NAME
        git config --global user.email USER_MAIL
    - name: Add Files
      run: |
        pwd && ls -la
        #git lfs checkout
        #git lfs install
        git lfs track *.csv
        git add .gitattributes
        git add original_datasets/*.csv
        git commit -m "Extracting zip files to CSV"
        git push origin HEAD:main
