name: Extract Zip Files Operations

on:
  workflow_dispatch:

jobs:
  extract_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content
    - name: List current dir....
      run: ls -la "/home/runner/work/Capstone-Analysis/Capstone-Analysis"    
    - name: Download Artifact
      env:
        USER_NAME: ${{secrets.GH_NAME}}
        USER_MAIL: ${{secrets.GH_EMAIL}} 
        USER_TOKEN: ${{secrets.PUBLIC_REPO_ACCESS_TOKEN}}
      # uses: actions/download-artifact@v2
      # with:
      # name: file.zip
      # path: /original_zipfiles/
      run: |
        curl -L -H "Authorization:Bearer $USER_TOKEN" -o file.zip "https://api.github.com/repos/armonbc/Capstone-Analysis/actions/artifacts/608912866/zip"
        ls -la

    - name: Configure Git
      run: |
        git config --global user.name USER_NAME
        git config --global user.email USER_MAIL
    - name: Add Files
      run: |
        git add "file.zip"
        git commit -m "Add artifact"
    - name: Push to Public Repository
      uses: ad-m/github-push-action@master
      with:
        github_token: USER_TOKEN
        branch: main
